
package com.xavier.webservices.upandrunning.ch02.contractfirst.rewriteservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TempConvert", targetNamespace = "http://tempConvertURI.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TempConvert {


    /**
     * 
     * @param t
     * @return
     *     returns double
     */
    @WebMethod(operationName = "f2c", action = "http://tempConvertURI.org/f2c")
    @WebResult(name = "f2cResult", targetNamespace = "http://tempConvertURI.org/")
    @RequestWrapper(localName = "f2c", targetNamespace = "http://tempConvertURI.org/", className = "com.xavier.webservices.upandrunning.ch02.contractfirst.rewriteservice.client.F2C")
    @ResponseWrapper(localName = "f2cResponse", targetNamespace = "http://tempConvertURI.org/", className = "com.xavier.webservices.upandrunning.ch02.contractfirst.rewriteservice.client.F2CResponse")
    @Action(input = "http://tempConvertURI.org/f2c", output = "http://tempConvertURI.org/TempConvert/f2cResponse")
    public double f2C(
        @WebParam(name = "t", targetNamespace = "http://tempConvertURI.org/")
        double t);

    /**
     * 
     * @param t
     * @return
     *     returns double
     */
    @WebMethod(operationName = "c2f", action = "http://tempConvertURI.org/c2f")
    @WebResult(name = "c2fResult", targetNamespace = "http://tempConvertURI.org/")
    @RequestWrapper(localName = "c2f", targetNamespace = "http://tempConvertURI.org/", className = "com.xavier.webservices.upandrunning.ch02.contractfirst.rewriteservice.client.C2F")
    @ResponseWrapper(localName = "c2fResponse", targetNamespace = "http://tempConvertURI.org/", className = "com.xavier.webservices.upandrunning.ch02.contractfirst.rewriteservice.client.C2FResponse")
    @Action(input = "http://tempConvertURI.org/c2f", output = "http://tempConvertURI.org/TempConvert/c2fResponse")
    public double c2F(
        @WebParam(name = "t", targetNamespace = "http://tempConvertURI.org/")
        double t);

}
