
package com.xavier.webservices.upandrunning.ch03.fibcsoap12;

import java.net.MalformedURLException;
import java.net.URL;
import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RabbitCounterSOAP12Service", targetNamespace = "http://ch03.fib", wsdlLocation = "http://localhost:8888/rcs12?wsdl")
@HandlerChain(file = "handler-chain.xml")
public class RabbitCounterSOAP12Service
    extends Service
{

    private final static URL RABBITCOUNTERSOAP12SERVICE_WSDL_LOCATION;
    private final static WebServiceException RABBITCOUNTERSOAP12SERVICE_EXCEPTION;
    private final static QName RABBITCOUNTERSOAP12SERVICE_QNAME = new QName("http://ch03.fib", "RabbitCounterSOAP12Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/rcs12?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RABBITCOUNTERSOAP12SERVICE_WSDL_LOCATION = url;
        RABBITCOUNTERSOAP12SERVICE_EXCEPTION = e;
    }

    public RabbitCounterSOAP12Service() {
        super(__getWsdlLocation(), RABBITCOUNTERSOAP12SERVICE_QNAME);
    }

    public RabbitCounterSOAP12Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), RABBITCOUNTERSOAP12SERVICE_QNAME, features);
    }

    public RabbitCounterSOAP12Service(URL wsdlLocation) {
        super(wsdlLocation, RABBITCOUNTERSOAP12SERVICE_QNAME);
    }

    public RabbitCounterSOAP12Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RABBITCOUNTERSOAP12SERVICE_QNAME, features);
    }

    public RabbitCounterSOAP12Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RabbitCounterSOAP12Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RabbitCounterSOAP12
     */
    @WebEndpoint(name = "RabbitCounterSOAP12Port")
    public RabbitCounterSOAP12 getRabbitCounterSOAP12Port() {
        return super.getPort(new QName("http://ch03.fib", "RabbitCounterSOAP12Port"), RabbitCounterSOAP12.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RabbitCounterSOAP12
     */
    @WebEndpoint(name = "RabbitCounterSOAP12Port")
    public RabbitCounterSOAP12 getRabbitCounterSOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ch03.fib", "RabbitCounterSOAP12Port"), RabbitCounterSOAP12.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RABBITCOUNTERSOAP12SERVICE_EXCEPTION!= null) {
            throw RABBITCOUNTERSOAP12SERVICE_EXCEPTION;
        }
        return RABBITCOUNTERSOAP12SERVICE_WSDL_LOCATION;
    }

}
