
package com.xavier.webservices.upandrunning.ch02.ts.rpcclient;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TimeServer", targetNamespace = "http://ts.ch02.upandrunning.webservices.xavier.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface TimeServer {


    /**
     * 
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(name = "time_rseponse_elapsed", partName = "time_rseponse_elapsed")
    @Action(input = "http://ts.ch02.upandrunning.webservices.xavier.com/TimeServer/getTimeAsElapsedRequest", output = "http://ts.ch02.upandrunning.webservices.xavier.com/TimeServer/getTimeAsElapsedResponse")
    public long getTimeAsElapsed();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "time_response", partName = "time_response")
    @Action(input = "http://ts.ch02.upandrunning.webservices.xavier.com/TimeServer/getTimeAsStringRequest", output = "http://ts.ch02.upandrunning.webservices.xavier.com/TimeServer/getTimeAsStringResponse")
    public String getTimeAsString();

}
