
package com.xavier.webservices.upandrunning.ch02.ts.docclient;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TimeServer", targetNamespace = "http://ts.ch01.upandrunning.webservices.xavier.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TimeServer {


    /**
     * 
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTimeAsEclapsed", targetNamespace = "http://ts.ch01.upandrunning.webservices.xavier.com/", className = "com.xavier.webservices.upandrunning.ch02.ts.docclient.GetTimeAsEclapsed")
    @ResponseWrapper(localName = "getTimeAsEclapsedResponse", targetNamespace = "http://ts.ch01.upandrunning.webservices.xavier.com/", className = "com.xavier.webservices.upandrunning.ch02.ts.docclient.GetTimeAsEclapsedResponse")
    @Action(input = "http://ts.ch01.upandrunning.webservices.xavier.com/TimeServer/getTimeAsEclapsedRequest", output = "http://ts.ch01.upandrunning.webservices.xavier.com/TimeServer/getTimeAsEclapsedResponse")
    public long getTimeAsEclapsed();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTimeAsString", targetNamespace = "http://ts.ch01.upandrunning.webservices.xavier.com/", className = "com.xavier.webservices.upandrunning.ch02.ts.docclient.GetTimeAsString")
    @ResponseWrapper(localName = "getTimeAsStringResponse", targetNamespace = "http://ts.ch01.upandrunning.webservices.xavier.com/", className = "com.xavier.webservices.upandrunning.ch02.ts.docclient.GetTimeAsStringResponse")
    @Action(input = "http://ts.ch01.upandrunning.webservices.xavier.com/TimeServer/getTimeAsStringRequest", output = "http://ts.ch01.upandrunning.webservices.xavier.com/TimeServer/getTimeAsStringResponse")
    public String getTimeAsString();

}
