
package com.xavier.webservices.upandrunning.ch03.binary.mtomattachmentclient;

import java.util.List;
import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SkiImageService", targetNamespace = "http://mtomattachmentservice.binary.ch03.upandrunning.webservices.xavier.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SkiImageService {


    /**
     * 
     * @return
     *     returns java.util.List<javax.activation.DataHandler>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getImages", targetNamespace = "http://mtomattachmentservice.binary.ch03.upandrunning.webservices.xavier.com/", className = "com.xavier.webservices.upandrunning.ch03.binary.mtomattachmentclient.GetImages")
    @ResponseWrapper(localName = "getImagesResponse", targetNamespace = "http://mtomattachmentservice.binary.ch03.upandrunning.webservices.xavier.com/", className = "com.xavier.webservices.upandrunning.ch03.binary.mtomattachmentclient.GetImagesResponse")
    @Action(input = "http://mtomattachmentservice.binary.ch03.upandrunning.webservices.xavier.com/SkiImageService/getImagesRequest", output = "http://mtomattachmentservice.binary.ch03.upandrunning.webservices.xavier.com/SkiImageService/getImagesResponse")
    public List<DataHandler> getImages();

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.activation.DataHandler
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getImage", targetNamespace = "http://mtomattachmentservice.binary.ch03.upandrunning.webservices.xavier.com/", className = "com.xavier.webservices.upandrunning.ch03.binary.mtomattachmentclient.GetImage")
    @ResponseWrapper(localName = "getImageResponse", targetNamespace = "http://mtomattachmentservice.binary.ch03.upandrunning.webservices.xavier.com/", className = "com.xavier.webservices.upandrunning.ch03.binary.mtomattachmentclient.GetImageResponse")
    @Action(input = "http://mtomattachmentservice.binary.ch03.upandrunning.webservices.xavier.com/SkiImageService/getImageRequest", output = "http://mtomattachmentservice.binary.ch03.upandrunning.webservices.xavier.com/SkiImageService/getImageResponse")
    public DataHandler getImage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
