
package com.xavier.webservices.upandrunning.ch02.tsa.clienttsa;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AnnotatedTimeServer", targetNamespace = "http://ch02.tsa")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AnnotatedTimeServer {


    /**
     * 
     * @return
     *     returns long
     */
    @WebMethod(operationName = "time_elapsed")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "time_elapsed", targetNamespace = "http://ch02.tsa", className = "com.xavier.webservices.upandrunning.ch02.tsa.clienttsa.TimeElapsed")
    @ResponseWrapper(localName = "time_elapsedResponse", targetNamespace = "http://ch02.tsa", className = "com.xavier.webservices.upandrunning.ch02.tsa.clienttsa.TimeElapsedResponse")
    @Action(input = "http://ch02.tsa/AnnotatedTimeServer/time_elapsedRequest", output = "http://ch02.tsa/AnnotatedTimeServer/time_elapsedResponse")
    public long timeElapsed();

    /**
     * 
     * @param clientMessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "time_string")
    @WebResult(name = "ts_out", targetNamespace = "http://ch02.tsa")
    @RequestWrapper(localName = "time_string", targetNamespace = "http://ch02.tsa", className = "com.xavier.webservices.upandrunning.ch02.tsa.clienttsa.TimeString")
    @ResponseWrapper(localName = "time_stringResponse", targetNamespace = "http://ch02.tsa", className = "com.xavier.webservices.upandrunning.ch02.tsa.clienttsa.TimeStringResponse")
    @Action(input = "http://ch02.tsa/AnnotatedTimeServer/time_stringRequest", output = "http://ch02.tsa/AnnotatedTimeServer/time_stringResponse")
    public String timeString(
        @WebParam(name = "client_message", targetNamespace = "http://ch02.tsa")
        String clientMessage);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "acceptInput", targetNamespace = "http://ch02.tsa", className = "com.xavier.webservices.upandrunning.ch02.tsa.clienttsa.AcceptInput")
    @Action(input = "http://ch02.tsa/AnnotatedTimeServer/acceptInput")
    public void acceptInput(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
