
package com.xavier.webservices.upandrunning.ch02.tsa.clienttsa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RevisedTimeServer", targetNamespace = "http://ch02.tsa", wsdlLocation = "http://localhost:8888/tsa?wsdl")
public class RevisedTimeServer
    extends Service
{

    private final static URL REVISEDTIMESERVER_WSDL_LOCATION;
    private final static WebServiceException REVISEDTIMESERVER_EXCEPTION;
    private final static QName REVISEDTIMESERVER_QNAME = new QName("http://ch02.tsa", "RevisedTimeServer");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/tsa?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REVISEDTIMESERVER_WSDL_LOCATION = url;
        REVISEDTIMESERVER_EXCEPTION = e;
    }

    public RevisedTimeServer() {
        super(__getWsdlLocation(), REVISEDTIMESERVER_QNAME);
    }

    public RevisedTimeServer(WebServiceFeature... features) {
        super(__getWsdlLocation(), REVISEDTIMESERVER_QNAME, features);
    }

    public RevisedTimeServer(URL wsdlLocation) {
        super(wsdlLocation, REVISEDTIMESERVER_QNAME);
    }

    public RevisedTimeServer(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REVISEDTIMESERVER_QNAME, features);
    }

    public RevisedTimeServer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RevisedTimeServer(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AnnotatedTimeServer
     */
    @WebEndpoint(name = "AnnotatedTimeServerPort")
    public AnnotatedTimeServer getAnnotatedTimeServerPort() {
        return super.getPort(new QName("http://ch02.tsa", "AnnotatedTimeServerPort"), AnnotatedTimeServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnnotatedTimeServer
     */
    @WebEndpoint(name = "AnnotatedTimeServerPort")
    public AnnotatedTimeServer getAnnotatedTimeServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ch02.tsa", "AnnotatedTimeServerPort"), AnnotatedTimeServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REVISEDTIMESERVER_EXCEPTION!= null) {
            throw REVISEDTIMESERVER_EXCEPTION;
        }
        return REVISEDTIMESERVER_WSDL_LOCATION;
    }

}
